name: "Android build"
on:
  push:
    branches:
      - master

jobs:
  android-apk-build:
    name: Building android apk
    runs-on: ubuntu-latest
    steps:
      - name: Clone the current repo
        uses: actions/checkout@v3
      
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: "gradle"
      - name: Install Sdk
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 9.0
        
      - name: Installing model
        run: |
          cd examples/whisper.android.java
          mkdir -p app/src/main/assets/models
          cd app/src/main/assets/models
          curl -L --output ggml-tiny.en.bin https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.en.bin

      - name: Getting a sample
        run: |
          cd examples/whisper.android.java
          mkdir -p app/src/main/assets/samples
          cd app/src/main/assets/samples
          curl -O -L https://github.com/ggerganov/whisper.cpp/raw/master/samples/jfk.wav
          
      - name: Build
        run: |
          cd examples/whisper.android.java
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon
          
      - name: Upload to artifactory
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: whisper/examples/whisper.android/app/build/outputs/apk/release
